-- H2 兼容 DDL（供集成测试；与主 schema 同表结构，AUTO_INCREMENT → IDENTITY，内联 KEY → CREATE INDEX）
-- 字典类型
CREATE TABLE sys_dict_type (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  dict_name VARCHAR(128) NOT NULL,
  dict_type VARCHAR(64) NOT NULL,
  status TINYINT DEFAULT 1,
  remark VARCHAR(256),
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_sys_dict_type PRIMARY KEY (id),
  CONSTRAINT uk_sys_dict_type UNIQUE (dict_type)
);

-- 字典数据
CREATE TABLE sys_dict_data (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  dict_type VARCHAR(64) NOT NULL,
  dict_label VARCHAR(128) NOT NULL,
  dict_value VARCHAR(128) NOT NULL,
  sort INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_sys_dict_data PRIMARY KEY (id),
  CONSTRAINT uk_sys_dict_data UNIQUE (dict_type, dict_value)
);

-- 部门
CREATE TABLE sys_dept (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  dept_name VARCHAR(64) NOT NULL,
  parent_id BIGINT DEFAULT 0,
  sort INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_sys_dept PRIMARY KEY (id)
);
CREATE INDEX idx_sys_dept_parent ON sys_dept (parent_id);

-- 用户
CREATE TABLE sys_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  username VARCHAR(64) NOT NULL,
  password VARCHAR(128) NOT NULL,
  nickname VARCHAR(64),
  dept_id BIGINT,
  status TINYINT DEFAULT 1,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_sys_user PRIMARY KEY (id),
  CONSTRAINT uk_sys_user_username UNIQUE (username)
);
CREATE INDEX idx_sys_user_dept ON sys_user (dept_id);

-- 角色
CREATE TABLE sys_role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  role_name VARCHAR(64) NOT NULL,
  role_key VARCHAR(64) NOT NULL,
  sort INT DEFAULT 0,
  status TINYINT DEFAULT 1,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_sys_role PRIMARY KEY (id),
  CONSTRAINT uk_sys_role_key UNIQUE (role_key)
);

-- 菜单（M=目录 C=菜单 F=按钮）
CREATE TABLE sys_menu (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  menu_name VARCHAR(64) NOT NULL,
  parent_id BIGINT DEFAULT 0,
  path VARCHAR(200),
  component VARCHAR(200),
  perms VARCHAR(100),
  menu_type CHAR(1) NOT NULL,
  icon VARCHAR(64),
  sort INT DEFAULT 0,
  visible TINYINT DEFAULT 1,
  status TINYINT DEFAULT 1,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_sys_menu PRIMARY KEY (id)
);
CREATE INDEX idx_sys_menu_parent ON sys_menu (parent_id);

-- 用户-角色 / 角色-菜单
CREATE TABLE sys_user_role (
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_sys_user_role PRIMARY KEY (user_id, role_id)
);
CREATE INDEX idx_sys_user_role_role ON sys_user_role (role_id);

CREATE TABLE sys_role_menu (
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_sys_role_menu PRIMARY KEY (role_id, menu_id)
);
CREATE INDEX idx_sys_role_menu_menu ON sys_role_menu (menu_id);

-- 项目
CREATE TABLE project (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  project_code VARCHAR(32) NOT NULL,
  project_name VARCHAR(128) NOT NULL,
  project_type VARCHAR(64) NOT NULL,
  investment_amount DECIMAL(18,2) NOT NULL,
  dept_id BIGINT,
  plan_start_date DATE,
  plan_end_date DATE,
  valid_until DATE,
  description VARCHAR(512),
  status VARCHAR(32) NOT NULL,
  source VARCHAR(32) DEFAULT 'MANUAL',
  issue_time DATETIME,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_project PRIMARY KEY (id),
  CONSTRAINT uk_project_code UNIQUE (project_code)
);
CREATE INDEX idx_project_type ON project (project_type);
CREATE INDEX idx_project_dept ON project (dept_id);
CREATE INDEX idx_project_status_time ON project (status, create_time);

-- 论证记录
CREATE TABLE project_review (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  project_id BIGINT NOT NULL,
  info_complete VARCHAR(16),
  three_important VARCHAR(16),
  split_project VARCHAR(16),
  interface_confusion VARCHAR(16),
  opinion VARCHAR(512),
  result VARCHAR(16) NOT NULL,
  review_by BIGINT,
  review_time DATETIME,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_project_review PRIMARY KEY (id)
);
CREATE INDEX idx_project_review_project ON project_review (project_id);

-- 审核记录
CREATE TABLE project_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  project_id BIGINT NOT NULL,
  opinion VARCHAR(512),
  result VARCHAR(16) NOT NULL,
  audit_by BIGINT,
  audit_time DATETIME,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_project_audit PRIMARY KEY (id)
);
CREATE INDEX idx_project_audit_project ON project_audit (project_id);

-- 自动化测试-场景
CREATE TABLE at_scenario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500),
  base_url VARCHAR(255),
  variables CLOB,
  create_by BIGINT,
  create_time DATETIME,
  update_by BIGINT,
  update_time DATETIME,
  CONSTRAINT pk_at_scenario PRIMARY KEY (id)
);

-- 自动化测试-步骤
CREATE TABLE at_step (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  scenario_id BIGINT NOT NULL,
  step_order INT NOT NULL,
  name VARCHAR(100),
  params CLOB NOT NULL,
  create_time DATETIME,
  update_time DATETIME,
  CONSTRAINT pk_at_step PRIMARY KEY (id)
);
CREATE INDEX idx_at_step_scenario ON at_step (scenario_id);

-- 自动化测试-执行记录
CREATE TABLE at_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  scenario_id BIGINT,
  status TINYINT,
  fail_step_id BIGINT,
  error_msg VARCHAR(1000),
  start_time DATETIME,
  end_time DATETIME,
  trigger_by BIGINT,
  create_time DATETIME,
  CONSTRAINT pk_at_run PRIMARY KEY (id)
);
CREATE INDEX idx_at_run_scenario ON at_run (scenario_id);

-- 自动化测试-步骤结果
CREATE TABLE at_step_result (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  run_id BIGINT NOT NULL,
  step_id BIGINT,
  step_order INT,
  name VARCHAR(100),
  status TINYINT,
  request_snapshot CLOB,
  response_snapshot CLOB,
  assert_detail CLOB,
  error_msg VARCHAR(1000),
  start_time DATETIME,
  end_time DATETIME,
  CONSTRAINT pk_at_step_result PRIMARY KEY (id)
);
CREATE INDEX idx_at_step_result_run ON at_step_result (run_id);
